# Example configuration demonstrating NVIDIA Nsight Systems profiling
suite: "nsight_profiling_demo"
name: "Nsight Systems Profiling Demo"
description: "Demonstrates NVIDIA Nsight Systems profiling with vLLM server"
tags: ["demo", "nsight", "profiling", "cuda", "performance"]

# Server Configuration
server:
  model: "meta-llama/Meta-Llama-3-8B"
  dtype: "bfloat16"
  tensor_parallel_size: 4
  gpu_memory_utilization: 0.8
  max_model_len: 2048
  host: "127.0.0.1"
  port: null  # Auto-assigned

# Benchmark Configuration
benchmark:
  backend: "vllm"
  endpoint: "/v1/completions"
  dataset_name: "sharegpt"
  num_prompts: 1  # Small number for profiling demo
  max_concurrency: 4
  temperature: 0.0
  max_tokens: 64
  profile: true  # This will be automatically disabled when Nsight is enabled
  save_result: true
  save_detailed: true

# System Configuration with Nsight Profiling
system:
  monitor_gpu: true
  monitor_cpu: true
  monitor_memory: true
  monitoring_interval: 1.0
  
  # Disable torch profiler when using Nsight
  enable_profiling: false
  
  # Nsight Systems profiling configuration
  enable_nsight: true
  nsight_output_dir: "nsight_traces"  # Will be created as results/{run_id}/nsight_traces/
  nsight_trace_fork: true
  nsight_cuda_graph_trace: "node"
  nsight_delay: 30  # Wait 30 seconds before starting profiling
  nsight_duration: 120  # Profile for 2 minutes (None = manual stop)
  
  # High verbosity Nsight options for comprehensive analysis
  nsight_trace: "cuda,cudnn,mpi,osrt,nvtx,openmp"  # Enable comprehensive tracing: CUDA, cuDNN, MPI, OS runtime, NVTX, OpenMP
  nsight_cuda_trace_all_apis: true  # Trace all CUDA APIs (high overhead but comprehensive)
  nsight_cuda_memory_usage: true  # Track GPU memory usage by CUDA kernels
  nsight_cuda_backtrace: "all"  # Collect backtraces for all CUDA APIs
  nsight_cuda_flush_interval: 1000  # Flush CUDA buffers every 1 second
  nsight_sample: "process-tree"  # CPU sampling scope
  nsight_sampling_frequency: 8  # 8Hz sampling frequency (converted to period, results in 125000 period - minimum valid)
  nsight_cpu_core_events: "2"  # Instructions Retired (default)
  nsight_event_sample: "system-wide"  # Enable event sampling
  nsight_stats: true  # Generate summary statistics
  nsight_export: "text"  # Export additional text format
  
  # Additional tracing options (these are now included in nsight_trace above)
  nsight_mpi_trace: true  # Enable MPI tracing for collective operations
  nsight_osrt_trace: true  # Enable OS runtime tracing for system calls
  
  # Advanced CPU tracing options
  nsight_cpu_trace_children: true  # Trace child processes
  nsight_cpu_trace_fork: true  # Trace fork/exec calls
  nsight_cpu_trace_syscalls: true  # Trace system calls (via osrt)
  nsight_cpu_trace_locks: true  # Trace mutex/lock operations (via osrt)
  nsight_cpu_trace_memory: true  # Trace memory allocations/deallocations (via osrt)
  nsight_cpu_trace_io: true  # Trace I/O operations (via osrt)
  nsight_cpu_trace_network: true  # Trace network operations (via osrt)
  nsight_cpu_trace_threads: true  # Trace thread creation/destruction (via osrt)
  nsight_cpu_trace_signals: true  # Trace signal handling (via osrt)
  nsight_cpu_trace_timers: true  # Trace timer operations (via osrt)
  
  # CPU sampling and profiling options
  nsight_cpu_sample_rate: 1000  # CPU sampling rate in Hz (higher = more overhead)
  nsight_cpu_sample_scope: "process-tree"  # process, process-tree, system
  nsight_cpu_sample_cpu: true  # Sample CPU usage
  nsight_cpu_sample_memory: true  # Sample memory usage
  nsight_cpu_sample_io: true  # Sample I/O operations
  nsight_cpu_sample_network: true  # Sample network operations
  
  # CPU performance counters
  nsight_cpu_counters: true  # Enable CPU performance counters
  nsight_cpu_counter_events: "cycles,instructions,cache-misses,branch-misses"  # CPU events to track
  nsight_cpu_counter_scope: "process-tree"  # Counter scope
  
  # Call stack and symbol resolution
  nsight_cpu_call_stacks: true  # Capture call stacks
  nsight_cpu_symbols: true  # Resolve function symbols
  nsight_cpu_source_lines: true  # Include source line information
  nsight_cpu_debug_info: true  # Include debug information
  
  # Additional CPU profiling options
  nsight_cpu_kernel_trace: true  # Trace CPU kernel functions
  nsight_cpu_user_trace: true  # Trace user-space functions
  nsight_cpu_context_switches: true  # Track context switches
  nsight_cpu_memory_bandwidth: true  # Track memory bandwidth usage
  nsight_cpu_cache_events: true  # Track cache events
  nsight_cpu_branch_events: true  # Track branch prediction events
  
  # Advanced sampling options
  nsight_cpu_sample_all_threads: true  # Sample all threads
  nsight_cpu_sample_kernel: true  # Sample kernel space
  nsight_cpu_sample_user: true  # Sample user space
  nsight_cpu_sample_idle: false  # Sample idle time (usually not needed)

# Export Configuration
export:
  enable_export: true
  export_csv: true
  export_influxdb: false
  export_dir: "exports"
  csv_summary: true
  csv_requests: true
  csv_system: true

# Output Configuration
output_path: "results/nsight_profiling_demo.json"
timeout: 600  # 10 minutes
max_retries: 2
dry_run: false
